[package]
name = "generate-axum-csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
csv = "1.3.0"
dotenv = "0.15.0"
tokio = { version = "1.36.0", features = ["full"] }
